"""Add arcface_embedding column to Employee

Revision ID: c27f71ee62bf
Revises: 
Create Date: 2025-07-23 17:42:51.107012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27f71ee62bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arcface_embedding', sa.PickleType(), nullable=True))
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.BLOB(), nullable=False))
        batch_op.drop_column('arcface_embedding')

    # ### end Alembic commands ###
